const rules = {
  "proxy-groups": [
    {
      hidden: false,
      icon: "https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/adjust.svg",
      "include-all": true,
      interval: 300,
      lazy: true,
      "max-failed-times": 3,
      name: "节点选择",
      proxies: ["自动选择"],
      timeout: 3000,
      type: "select",
      url: "https://www.google.com/generate_204",
    },
    {
      hidden: false,
      icon: "https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/speed.svg",
      "include-all": true,
      interval: 300,
      lazy: true,
      "max-failed-times": 3,
      name: "自动选择",
      timeout: 3000,
      tolerance: 50,
      type: "url-test",
      url: "https://www.google.com/generate_204",
    },
    {
      hidden: false,
      icon: "https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/telegram.svg",
      "include-all": true,
      interval: 300,
      lazy: true,
      "max-failed-times": 3,
      name: "电报消息",
      proxies: ["节点选择", "全球直连"],
      timeout: 3000,
      type: "select",
      url: "https://www.google.com/generate_204",
    },
    {
      hidden: false,
      icon: "https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/telegram.svg",
      "include-all": true,
      interval: 300,
      lazy: true,
      "max-failed-times": 3,
      name: "OpenAi",
      proxies: ["节点选择", "全球直连"],
      timeout: 3000,
      type: "select",
      url: "https://www.google.com/generate_204",
    },
    {
      hidden: false,
      icon: "https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/youtube.svg",
      "include-all": true,
      interval: 300,
      lazy: true,
      "max-failed-times": 3,
      name: "油管视频",
      proxies: ["节点选择", "全球直连"],
      timeout: 3000,
      type: "select",
      url: "https://www.google.com/generate_204",
    },
    {
      hidden: false,
      icon: "https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/google.svg",
      "include-all": true,
      interval: 300,
      lazy: true,
      "max-failed-times": 3,
      name: "谷歌服务",
      proxies: ["节点选择", "全球直连"],
      timeout: 3000,
      type: "select",
      url: "https://www.google.com/generate_204",
    },
    {
      hidden: false,
      icon: "https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/microsoft.svg",
      "include-all": true,
      interval: 300,
      lazy: true,
      "max-failed-times": 3,
      name: "微软Bing",
      proxies: ["节点选择", "全球直连", "OpenAi"],
      timeout: 3000,
      type: "select",
      url: "https://www.google.com/generate_204",
    },
    {
      hidden: false,
      icon: "https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/microsoft.svg",
      "include-all": true,
      interval: 300,
      lazy: true,
      "max-failed-times": 3,
      name: "微软云盘",
      proxies: ["节点选择", "全球直连"],
      timeout: 3000,
      type: "select",
      url: "https://www.google.com/generate_204",
    },
    {
      hidden: false,
      icon: "https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/link.svg",
      interval: 300,
      lazy: true,
      "max-failed-times": 3,
      name: "全球直连",
      proxies: ["DIRECT"],
      timeout: 3000,
      type: "select",
      url: "https://www.google.com/generate_204",
    },
  ],
  "rule-providers": {
    apple: {
      behavior: "domain",
      interval: 86400,
      path: "./ruleset/apple.yaml",
      type: "http",
      url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt",
    },
    cncidr: {
      behavior: "ipcidr",
      interval: 86400,
      path: "./ruleset/cncidr.yaml",
      type: "http",
      url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt",
    },
    direct: {
      behavior: "domain",
      interval: 86400,
      path: "./ruleset/direct.yaml",
      type: "http",
      url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt",
    },
    gfw: {
      behavior: "domain",
      interval: 86400,
      path: "./ruleset/gfw.yaml",
      type: "http",
      url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt",
    },
    google: {
      behavior: "domain",
      interval: 86400,
      path: "./ruleset/google.yaml",
      type: "http",
      url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt",
    },
    icloud: {
      behavior: "domain",
      interval: 86400,
      path: "./ruleset/icloud.yaml",
      type: "http",
      url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt",
    },
    lancidr: {
      behavior: "ipcidr",
      interval: 86400,
      path: "./ruleset/lancidr.yaml",
      type: "http",
      url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt",
    },
    private: {
      behavior: "domain",
      interval: 86400,
      path: "./ruleset/private.yaml",
      type: "http",
      url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt",
    },
    proxy: {
      behavior: "domain",
      interval: 86400,
      path: "./ruleset/proxy.yaml",
      type: "http",
      url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt",
    },
    reject: {
      behavior: "domain",
      interval: 86400,
      path: "./ruleset/reject.yaml",
      type: "http",
      url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt",
    },
    telegramcidr: {
      behavior: "ipcidr",
      interval: 86400,
      path: "./ruleset/telegramcidr.yaml",
      type: "http",
      url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt",
    },
    "tld-not-cn": {
      behavior: "domain",
      interval: 86400,
      path: "./ruleset/tld-not-cn.yaml",
      type: "http",
      url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt",
    },
  },
  rules: [
    "DOMAIN,clash.razord.top,全球直连",
    "DOMAIN,yacd.haishan.me,全球直连",
    "RULE-SET,reject,REJECT",
    "RULE-SET,icloud,全球直连",
    "RULE-SET,apple,全球直连",
    "RULE-SET,google,节点选择",
    "RULE-SET,proxy,节点选择",
    "RULE-SET,direct,全球直连",
    "RULE-SET,private,全球直连",
    "RULE-SET,gfw,全球直连",
    "RULE-SET,tld-not-cn,全球直连",
    "RULE-SET,telegramcidr,节点选择",
    "RULE-SET,cncidr,全球直连",
    "RULE-SET,lancidr,全球直连",
    "GEOIP,LAN,全球直连",
    "GEOIP,CN,全球直连",
    "DOMAIN-SUFFIX,googleapis.cn,节点选择",
    "DOMAIN-SUFFIX,gstatic.com,节点选择",
    "DOMAIN,v2rayse.com,节点选择",
    "DOMAIN-SUFFIX,open.spotify.com,全球直连",
    "DOMAIN-KEYWORD,spotify,节点选择",
    "DOMAIN-KEYWORD,openai,OpenAi",
    "DOMAIN-KEYWORD,chatgpt,OpenAi",
    "DOMAIN-KEYWORD,claude,OpenAi",
    "DOMAIN-KEYWORD,anthropic,OpenAi",
    "DOMAIN-KEYWORD,z-library,OpenAi",
    "DOMAIN,gemini.google.com,OpenAi",
    "DOMAIN-SUFFIX,singlelogin.re,OpenAi",
    "DOMAIN-SUFFIX,singlelogin.rs,OpenAi",
    "DOMAIN-SUFFIX,intellij.net,OpenAi",
    "DOMAIN-SUFFIX,auth0.com,OpenAi",
    "DOMAIN-SUFFIX,cloudflare.com,OpenAi",
    "DOMAIN-SUFFIX,chatgpt.com,OpenAi",
    "DOMAIN-SUFFIX,client-api.arkoselabs.com,OpenAi",
    "DOMAIN-SUFFIX,events.statsigapi.net,OpenAi",
    "DOMAIN-SUFFIX,featuregates.org,OpenAi",
    "DOMAIN-SUFFIX,identrust.com,OpenAi",
    "DOMAIN-SUFFIX,intercom.io,OpenAi",
    "DOMAIN-SUFFIX,intercomcdn.com,OpenAi",
    "DOMAIN-SUFFIX,oaistatic.com,OpenAi",
    "DOMAIN-SUFFIX,oaiusercontent.com,OpenAi",
    "DOMAIN-SUFFIX,openai.com,OpenAi",
    "DOMAIN-SUFFIX,claude.ai,OpenAi",
    "DOMAIN-SUFFIX,anthropic.com,OpenAi",
    "DOMAIN-SUFFIX,s-cdn.anthropic.com,OpenAi",
    "DOMAIN-SUFFIX,a-api.anthropic.com,OpenAi",
    "DOMAIN-SUFFIX,statsig.anthropic.com,OpenAi",
    "DOMAIN-SUFFIX,openaiapi-site.azureedge.net,OpenAi",
    "DOMAIN-SUFFIX,sentry.io,OpenAi",
    "DOMAIN-SUFFIX,stripe.com,OpenAi",
    "PROCESS-NAME,OneDrive,微软云盘",
    "PROCESS-NAME,OneDriveUpdater,微软云盘",
    "DOMAIN-KEYWORD,1drv,微软云盘",
    "DOMAIN-KEYWORD,onedrive,微软云盘",
    "DOMAIN-KEYWORD,skydrive,微软云盘",
    "DOMAIN-SUFFIX,livefilestore.com,微软云盘",
    "DOMAIN-SUFFIX,oneclient.sfx.ms,微软云盘",
    "DOMAIN-SUFFIX,onedrive.com,微软云盘",
    "DOMAIN-SUFFIX,onedrive.live.com,微软云盘",
    "DOMAIN-SUFFIX,photos.live.com,微软云盘",
    "DOMAIN-SUFFIX,sharepoint.com,微软云盘",
    "DOMAIN-SUFFIX,sharepointonline.com,微软云盘",
    "DOMAIN-SUFFIX,skydrive.wns.windows.com,微软云盘",
    "DOMAIN-SUFFIX,spoprod-a.akamaihd.net,微软云盘",
    "DOMAIN-SUFFIX,storage.live.com,微软云盘",
    "DOMAIN-SUFFIX,storage.msn.com,微软云盘",
    "DOMAIN-SUFFIX,vscode.dev,微软Bing",
    "DOMAIN-SUFFIX,bing.com,微软Bing",
    "DOMAIN-SUFFIX,copilot.microsoft.com,微软Bing",
    "DOMAIN-SUFFIX,t.me,电报消息",
    "DOMAIN-SUFFIX,tdesktop.com,电报消息",
    "DOMAIN-SUFFIX,telegra.ph,电报消息",
    "DOMAIN-SUFFIX,telegram.me,电报消息",
    "DOMAIN-SUFFIX,telegram.org,电报消息",
    "DOMAIN-SUFFIX,telesco.pe,电报消息",
    "DOMAIN,alt1-mtalk.google.com,谷歌服务",
    "DOMAIN,alt2-mtalk.google.com,谷歌服务",
    "DOMAIN,alt3-mtalk.google.com,谷歌服务",
    "DOMAIN,alt4-mtalk.google.com,谷歌服务",
    "DOMAIN,alt5-mtalk.google.com,谷歌服务",
    "DOMAIN,alt6-mtalk.google.com,谷歌服务",
    "DOMAIN,alt7-mtalk.google.com,谷歌服务",
    "DOMAIN,alt8-mtalk.google.com,谷歌服务",
    "DOMAIN,mtalk.google.com,谷歌服务",
    "DOMAIN-KEYWORD,youtube,油管视频",
    "DOMAIN,youtubei.googleapis.com,油管视频",
    "DOMAIN,yt3.ggpht.com,油管视频",
    "DOMAIN-SUFFIX,googlevideo.com,油管视频",
    "DOMAIN-SUFFIX,gvt2.com,油管视频",
    "DOMAIN-SUFFIX,withyoutube.com,油管视频",
    "DOMAIN-SUFFIX,youtu.be,油管视频",
    "DOMAIN-SUFFIX,youtube-nocookie.com,油管视频",
    "DOMAIN-SUFFIX,youtube.com,油管视频",
    "DOMAIN-SUFFIX,youtubeeducation.com,油管视频",
    "DOMAIN-SUFFIX,youtubegaming.com,油管视频",
    "DOMAIN-SUFFIX,youtubekids.com,油管视频",
    "DOMAIN-SUFFIX,yt.be,油管视频",
    "DOMAIN-SUFFIX,ytimg.com,油管视频",
    "DOMAIN-SUFFIX,eu,节点选择",
    "DOMAIN-SUFFIX,hk,节点选择",
    "DOMAIN-SUFFIX,jp,节点选择",
    "DOMAIN-SUFFIX,kr,节点选择",
    "DOMAIN-SUFFIX,sg,节点选择",
    "DOMAIN-SUFFIX,tw,节点选择",
    "DOMAIN-SUFFIX,uk,节点选择",
    "DOMAIN-SUFFIX,us,节点选择",
    "DOMAIN-SUFFIX,ca,节点选择",
    "DOMAIN-SUFFIX,micu.hk,全球直连",
    "DOMAIN-SUFFIX,ii00.cc,全球直连",
    "DOMAIN-SUFFIX,hxd.as174.com,全球直连",
    "DOMAIN-SUFFIX,emby.as174.com,节点选择",
    "DOMAIN-SUFFIX,tanhuatv.site,节点选择",
    "MATCH,节点选择",
  ],
};

export { rules };
