// 国内DNS服务器
const domesticNameservers = [
  "https://dns.alidns.com/dns-query", // 阿里云公共DNS
  "https://doh.pub/dns-query", // 腾讯DNSPod
  "https://doh.360.cn/dns-query", // 360安全DNS
];
// 国外DNS服务器
const foreignNameservers = [
  "https://1.1.1.1/dns-query", // Cloudflare(主)
  "https://1.0.0.1/dns-query", // Cloudflare(备)
  "https://208.67.222.222/dns-query", // OpenDNS(主)
  "https://208.67.220.220/dns-query", // OpenDNS(备)
  "https://194.242.2.2/dns-query", // Mullvad(主)
  "https://194.242.2.3/dns-query", // Mullvad(备)
];
// DNS配置
const dnsConfig = {
  enable: true,
  ipv6: false,
  "prefer-h3": true, // 如果 DNS 服务器支持 DoH3 会优先使用 h3
  "respect-rules": true, // 仅对符合规则的请求使用 DNS
  "enhanced-mode": "fake-ip", // 伪装 IP
  "fake-ip-range": "28.0.0.1/8",
  "fake-ip-filter": [
    "+.+m2m",
    "+.$injections.adguard.org",
    "+.$local.adguard.org",
    "+.+_tcp",
    "+.+bogon",
    "+.+_msdcs",
    "+.+lan",
    "+.+localdomain",
    "+.home.arpa",
    "+.10.in-addr.arpa",
    "+.16.172.in-addr.arpa",
    "+.17.172.in-addr.arpa",
    "+.18.172.in-addr.arpa",
    "+.19.172.in-addr.arpa",
    "+.20.172.in-addr.arpa",
    "+.21.172.in-addr.arpa",
    "+.22.172.in-addr.arpa",
    "+.23.172.in-addr.arpa",
    "+.24.172.in-addr.arpa",
    "+.25.172.in-addr.arpa",
    "+.26.172.in-addr.arpa",
    "+.27.172.in-addr.arpa",
    "+.28.172.in-addr.arpa",
    "+.29.172.in-addr.arpa",
    "+.30.172.in-addr.arpa",
    "+.31.172.in-addr.arpa",
    "+.168.192.in-addr.arpa",
    "+.254.169.in-addr.arpa",
    "dns.msftncsi.com",
    "*.srv.nintendo.net",
    "*.stun.playstation.net",
    "xbox.*.microsoft.com",
    "*.xboxlive.com",
    "*.turn.twilio.com",
    "*.stun.twilio.com",
    "stun.syncthing.net",
    "stun.*",
  ],
  "default-nameserver": ["223.5.5.5", "114.114.114.114", "1.1.1.1", "8.8.8.8"],
  nameserver: [...domesticNameservers, ...foreignNameservers],
  "proxy-server-nameserver": [...domesticNameservers, ...foreignNameservers],
  "nameserver-policy": {
    "dns.alidns.com": "quic://223.5.5.5:853",
    "doh.pub": "https://1.12.12.12/dns-query",
    "doh.360.cn": "101.198.198.198",
    "+.uc.cn": "quic://dns.alidns.com:853",
    "+.alibaba.com": "quic://dns.alidns.com:853",
    "*.alicdn.com": "quic://dns.alidns.com:853",
    "*.ialicdn.com": "quic://dns.alidns.com:853",
    "*.myalicdn.com": "quic://dns.alidns.com:853",
    "*.alidns.com": "quic://dns.alidns.com:853",
    "*.aliimg.com": "quic://dns.alidns.com:853",
    "+.aliyun.com": "quic://dns.alidns.com:853",
    "*.aliyuncs.com": "quic://dns.alidns.com:853",
    "*.alikunlun.com": "quic://dns.alidns.com:853",
    "*.alikunlun.net": "quic://dns.alidns.com:853",
    "*.cdngslb.com": "quic://dns.alidns.com:853",
    "+.alipay.com": "quic://dns.alidns.com:853",
    "+.alipay.cn": "quic://dns.alidns.com:853",
    "+.alipay.com.cn": "quic://dns.alidns.com:853",
    "*.alipayobjects.com": "quic://dns.alidns.com:853",
    "+.alibaba-inc.com": "quic://dns.alidns.com:853",
    "*.alibabausercontent.com": "quic://dns.alidns.com:853",
    "*.alibabadns.com": "quic://dns.alidns.com:853",
    "+.alibabachengdun.com": "quic://dns.alidns.com:853",
    "+.alicloudccp.com": "quic://dns.alidns.com:853",
    "+.alipan.com": "quic://dns.alidns.com:853",
    "+.aliyundrive.com": "quic://dns.alidns.com:853",
    "+.aliyundrive.net": "quic://dns.alidns.com:853",
    "+.cainiao.com": "quic://dns.alidns.com:853",
    "+.cainiao.com.cn": "quic://dns.alidns.com:853",
    "+.cainiaoyizhan.com": "quic://dns.alidns.com:853",
    "+.guoguo-app.com": "quic://dns.alidns.com:853",
    "+.etao.com": "quic://dns.alidns.com:853",
    "+.yitao.com": "quic://dns.alidns.com:853",
    "+.1688.com": "quic://dns.alidns.com:853",
    "+.amap.com": "quic://dns.alidns.com:853",
    "+.gaode.com": "quic://dns.alidns.com:853",
    "+.autonavi.com": "quic://dns.alidns.com:853",
    "+.dingtalk.com": "quic://dns.alidns.com:853",
    "+.mxhichina.com": "quic://dns.alidns.com:853",
    "+.soku.com": "quic://dns.alidns.com:853",
    "+.tb.cn": "quic://dns.alidns.com:853",
    "+.taobao.com": "quic://dns.alidns.com:853",
    "*.taobaocdn.com": "quic://dns.alidns.com:853",
    "*.tbcache.com": "quic://dns.alidns.com:853",
    "+.tmall.com": "quic://dns.alidns.com:853",
    "+.goofish.com": "quic://dns.alidns.com:853",
    "+.xiami.com": "quic://dns.alidns.com:853",
    "+.xiami.net": "quic://dns.alidns.com:853",
    "*.ykimg.com": "quic://dns.alidns.com:853",
    "+.youku.com": "quic://dns.alidns.com:853",
    "+.tudou.com": "quic://dns.alidns.com:853",
    "*.cibntv.net": "quic://dns.alidns.com:853",
    "+.ele.me": "quic://dns.alidns.com:853",
    "*.elemecdn.com": "quic://dns.alidns.com:853",
    "+.feizhu.com": "quic://dns.alidns.com:853",
    "+.taopiaopiao.com": "quic://dns.alidns.com:853",
    "+.fliggy.com": "quic://dns.alidns.com:853",
    "+.koubei.com": "quic://dns.alidns.com:853",
    "+.mybank.cn": "quic://dns.alidns.com:853",
    "+.mmstat.com": "quic://dns.alidns.com:853",
    "+.uczzd.cn": "quic://dns.alidns.com:853",
    "+.iconfont.cn": "quic://dns.alidns.com:853",
    "+.freshhema.com": "quic://dns.alidns.com:853",
    "+.hemamax.com": "quic://dns.alidns.com:853",
    "+.hemaos.com": "quic://dns.alidns.com:853",
    "+.hemashare.cn": "quic://dns.alidns.com:853",
    "+.shyhhema.com": "quic://dns.alidns.com:853",
    "+.sm.cn": "quic://dns.alidns.com:853",
    "+.npmmirror.com": "quic://dns.alidns.com:853",
    "+.alios.cn": "quic://dns.alidns.com:853",
    "+.wandoujia.com": "quic://dns.alidns.com:853",
    "+.aligames.com": "quic://dns.alidns.com:853",
    "+.25pp.com": "quic://dns.alidns.com:853",
    "*.aliapp.org": "quic://dns.alidns.com:853",
    "+.tanx.com": "quic://dns.alidns.com:853",
    "+.hellobike.com": "quic://dns.alidns.com:853",
    "*.hichina.com": "quic://dns.alidns.com:853",
    "*.yunos.com": "quic://dns.alidns.com:853",
    "*.qcloud.com": "https://doh.pub/dns-query",
    "*.gtimg.cn": "https://doh.pub/dns-query",
    "*.gtimg.com": "https://doh.pub/dns-query",
    "*.gtimg.com.cn": "https://doh.pub/dns-query",
    "*.gdtimg.com": "https://doh.pub/dns-query",
    "*.idqqimg.com": "https://doh.pub/dns-query",
    "*.udqqimg.com": "https://doh.pub/dns-query",
    "*.igamecj.com": "https://doh.pub/dns-query",
    "+.myapp.com": "https://doh.pub/dns-query",
    "*.myqcloud.com": "https://doh.pub/dns-query",
    "+.dnspod.com": "https://doh.pub/dns-query",
    "*.qpic.cn": "https://doh.pub/dns-query",
    "*.qlogo.cn": "https://doh.pub/dns-query",
    "+.qq.com": "https://doh.pub/dns-query",
    "+.qq.com.cn": "https://doh.pub/dns-query",
    "*.qqmail.com": "https://doh.pub/dns-query",
    "+.qzone.com": "https://doh.pub/dns-query",
    "*.tencent-cloud.net": "https://doh.pub/dns-query",
    "*.tencent-cloud.com": "https://doh.pub/dns-query",
    "+.tencent.com": "https://doh.pub/dns-query",
    "+.tencent.com.cn": "https://doh.pub/dns-query",
    "+.tencentmusic.com": "https://doh.pub/dns-query",
    "+.weixinbridge.com": "https://doh.pub/dns-query",
    "+.weixin.com": "https://doh.pub/dns-query",
    "+.weiyun.com": "https://doh.pub/dns-query",
    "+.soso.com": "https://doh.pub/dns-query",
    "+.sogo.com": "https://doh.pub/dns-query",
    "+.sogou.com": "https://doh.pub/dns-query",
    "*.sogoucdn.com": "https://doh.pub/dns-query",
    "*.roblox.cn": "https://doh.pub/dns-query",
    "+.robloxdev.cn": "https://doh.pub/dns-query",
    "+.wegame.com": "https://doh.pub/dns-query",
    "+.wegame.com.cn": "https://doh.pub/dns-query",
    "+.wegameplus.com": "https://doh.pub/dns-query",
    "+.cdn-go.cn": "https://doh.pub/dns-query",
    "*.tencentcs.cn": "https://doh.pub/dns-query",
    "*.qcloudimg.com": "https://doh.pub/dns-query",
    "+.dnspod.cn": "https://doh.pub/dns-query",
    "+.anticheatexpert.com": "https://doh.pub/dns-query",
    "url.cn": "https://doh.pub/dns-query",
    "*.qlivecdn.com": "https://doh.pub/dns-query",
    "*.tcdnlive.com": "https://doh.pub/dns-query",
    "*.dnsv1.com": "https://doh.pub/dns-query",
    "upos-sz-mirrorali.bilivideo.com": "quic://dns.alidns.com:853",
    "upos-sz-estgoss.bilivideo.com": "quic://dns.alidns.com:853",
    "upos-sz-mirrorbd.bilivideo.com": "180.76.76.76",
    "upos-sz-mirrorbos.bilivideo.com": "180.76.76.76",
    "acg.tv": "https://doh.pub/dns-query",
    "b23.tv": "https://doh.pub/dns-query",
    "+.bilibili.cn": "https://doh.pub/dns-query",
    "+.bilibili.com": "https://doh.pub/dns-query",
    "*.acgvideo.com": "https://doh.pub/dns-query",
    "*.bilivideo.com": "https://doh.pub/dns-query",
    "*.bilivideo.cn": "https://doh.pub/dns-query",
    "*.bilivideo.net": "https://doh.pub/dns-query",
    "*.hdslb.com": "https://doh.pub/dns-query",
    "*.biliimg.com": "https://doh.pub/dns-query",
    "*.biliapi.com": "https://doh.pub/dns-query",
    "*.biliapi.net": "https://doh.pub/dns-query",
    "+.biligame.com": "https://doh.pub/dns-query",
    "*.biligame.net": "https://doh.pub/dns-query",
    "+.bilicomic.com": "https://doh.pub/dns-query",
    "+.bilicomics.com": "https://doh.pub/dns-query",
    "*.bilicdn1.com": "https://doh.pub/dns-query",
    "+.mi.com": "https://doh.pub/dns-query",
    "+.duokan.com": "https://doh.pub/dns-query",
    "*.mi-img.com": "https://doh.pub/dns-query",
    "*.mi-idc.com": "https://doh.pub/dns-query",
    "*.xiaoaisound.com": "https://doh.pub/dns-query",
    "*.xiaomixiaoai.com": "https://doh.pub/dns-query",
    "*.mi-fds.com": "https://doh.pub/dns-query",
    "*.mifile.cn": "https://doh.pub/dns-query",
    "*.mijia.tech": "https://doh.pub/dns-query",
    "+.miui.com": "https://doh.pub/dns-query",
    "+.xiaomi.com": "https://doh.pub/dns-query",
    "+.xiaomi.cn": "https://doh.pub/dns-query",
    "+.xiaomi.net": "https://doh.pub/dns-query",
    "+.xiaomiev.com": "https://doh.pub/dns-query",
    "+.xiaomiyoupin.com": "https://doh.pub/dns-query",
    "+.bytedance.com.com": "180.184.2.2",
    "*.bytecdn.cn": "180.184.2.2",
    "*.volccdn.com": "180.184.2.2",
    "*.toutiaoimg.com": "180.184.2.2",
    "*.toutiaoimg.cn": "180.184.2.2",
    "*.toutiaostatic.com": "180.184.2.2",
    "*.toutiaovod.com": "180.184.2.2",
    "*.toutiaocloud.com": "180.184.2.2",
    "+.toutiaopage.com": "180.184.2.2",
    "+.feiliao.com": "180.184.2.2",
    "+.iesdouyin.com": "180.184.2.2",
    "*.pstatp.com": "180.184.2.2",
    "+.snssdk.com": "180.184.2.2",
    "*.bytegoofy.com": "180.184.2.2",
    "+.toutiao.com": "180.184.2.2",
    "+.feishu.cn": "180.184.2.2",
    "+.feishu.net": "180.184.2.2",
    "*.feishucdn.com": "180.184.2.2",
    "*.feishupkg.com": "180.184.2.2",
    "+.douyin.com": "180.184.2.2",
    "*.douyinpic.com": "180.184.2.2",
    "*.douyinstatic.com": "180.184.2.2",
    "*.douyincdn.com": "180.184.2.2",
    "*.douyinliving.com": "180.184.2.2",
    "*.douyinvod.com": "180.184.2.2",
    "+.huoshan.com": "180.184.2.2",
    "*.huoshanstatic.com": "180.184.2.2",
    "+.huoshanzhibo.com": "180.184.2.2",
    "+.ixigua.com": "180.184.2.2",
    "*.ixiguavideo.com": "180.184.2.2",
    "*.ixgvideo.com": "180.184.2.2",
    "*.byted-static.com": "180.184.2.2",
    "+.volces.com": "180.184.2.2",
    "+.baike.com": "180.184.2.2",
    "*.zjcdn.com": "180.184.2.2",
    "*.zijieapi.com": "180.184.2.2",
    "+.feelgood.cn": "180.184.2.2",
    "*.bytetcc.com": "180.184.2.2",
    "*.bytednsdoc.com": "180.184.2.2",
    "*.byteimg.com": "180.184.2.2",
    "*.byteacctimg.com": "180.184.2.2",
    "*.ibytedapm.com": "180.184.2.2",
    "+.oceanengine.com": "180.184.2.2",
    "+.91.com": "180.76.76.76",
    "+.hao123.com": "180.76.76.76",
    "+.baidu.cn": "180.76.76.76",
    "+.baidu.com": "180.76.76.76",
    "+.iqiyi.com": "180.76.76.76",
    "*.iqiyipic.com": "180.76.76.76",
    "*.baidubce.com": "180.76.76.76",
    "*.bcelive.com": "180.76.76.76",
    "*.baiducontent.com": "180.76.76.76",
    "*.baidustatic.com": "180.76.76.76",
    "*.bdstatic.com": "180.76.76.76",
    "*.bdimg.com": "180.76.76.76",
    "*.bcebos.com": "180.76.76.76",
    "*.baidupcs.com": "180.76.76.76",
    "*.baidubcr.com": "180.76.76.76",
    "*.yunjiasu-cdn.net": "180.76.76.76",
    "+.tieba.com": "180.76.76.76",
    "+.xiaodutv.com": "180.76.76.76",
    "*.shifen.com": "180.76.76.76",
    "*.jomodns.com": "180.76.76.76",
    "*.bdydns.com": "180.76.76.76",
    "*.jomoxc.com": "180.76.76.76",
    "*.duapp.com": "180.76.76.76",
    "*.antpcdn.com": "180.76.76.76",
    "*.qhimg.com": "https://doh.360.cn/dns-query",
    "*.qhimgs.com": "https://doh.360.cn/dns-query",
    "*.qhimgs?.com": "https://doh.360.cn/dns-query",
    "*.qhres.com": "https://doh.360.cn/dns-query",
    "*.qhres2.com": "https://doh.360.cn/dns-query",
    "*.qhmsg.com": "https://doh.360.cn/dns-query",
    "*.qhstatic.com": "https://doh.360.cn/dns-query",
    "*.qhupdate.com": "https://doh.360.cn/dns-query",
    "*.qihucdn.com": "https://doh.360.cn/dns-query",
    "+.360.com": "https://doh.360.cn/dns-query",
    "+.360.cn": "https://doh.360.cn/dns-query",
    "+.360.net": "https://doh.360.cn/dns-query",
    "+.360safe.com": "https://doh.360.cn/dns-query",
    "*.360tpcdn.com": "https://doh.360.cn/dns-query",
    "+.360os.com": "https://doh.360.cn/dns-query",
    "*.360webcache.com": "https://doh.360.cn/dns-query",
    "+.360kuai.com": "https://doh.360.cn/dns-query",
    "+.so.com": "https://doh.360.cn/dns-query",
    "+.haosou.com": "https://doh.360.cn/dns-query",
    "+.yunpan.cn": "https://doh.360.cn/dns-query",
    "+.yunpan.com": "https://doh.360.cn/dns-query",
    "+.yunpan.com.cn": "https://doh.360.cn/dns-query",
    "*.qh-cdn.com": "https://doh.360.cn/dns-query",
    "+.baomitu.com": "https://doh.360.cn/dns-query",
    "+.qiku.com": "https://doh.360.cn/dns-query",
    "+.securelogin.com.cn": ["system://", "system", "dhcp://system"],
    "captive.apple.com": ["system://", "system", "dhcp://system"],
    "hotspot.cslwifi.com": ["system://", "system", "dhcp://system"],
    "*.m2m": ["system://", "system", "dhcp://system"],
    "injections.adguard.org": ["system://", "system", "dhcp://system"],
    "local.adguard.org": ["system://", "system", "dhcp://system"],
    "*._tcp": ["system://", "system", "dhcp://system"],
    "*.bogon": ["system://", "system", "dhcp://system"],
    "*._msdcs": ["system://", "system", "dhcp://system"],
  },
};
// 规则集通用配置
const ruleProviderCommon = {
  type: "http",
  format: "yaml",
  interval: 86400,
};
// 规则集配置
const ruleProviders = {
  private: {
    ...ruleProviderCommon,
    behavior: "domain",
    path: "./ruleset/private.yaml",
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.yaml",
  },
  cn_domain: {
    ...ruleProviderCommon,
    behavior: "domain",
    path: "./ruleset/cn_domain.yaml",
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.yaml",
  },
  telegram_domain: {
    ...ruleProviderCommon,
    behavior: "domain",
    path: "./ruleset/telegram_domain.yaml",
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.yaml",
  },
  google_domain: {
    ...ruleProviderCommon,
    behavior: "domain",
    path: "./ruleset/google_domain.yaml",
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.yaml",
  },
  "geolocation-!cn": {
    ...ruleProviderCommon,
    behavior: "domain",
    path: "./ruleset/geolocation-!cn.yaml",
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.yaml",
  },
  cn_ip: {
    ...ruleProviderCommon,
    behavior: "ipcidr",
    path: "./ruleset/cn_ip.yaml",
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.yaml",
  },
  telegram_ip: {
    ...ruleProviderCommon,
    behavior: "ipcidr",
    path: "./ruleset/telegram_ip.yaml",
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.yaml",
  },
  google_ip: {
    ...ruleProviderCommon,
    behavior: "ipcidr",
    path: "./ruleset/google_ip.yaml",
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.yaml",
  },
  steam: {
    ...ruleProviderCommon,
    behavior: "classical",
    path: "./ruleset/steam.yaml",
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.yaml",
  },
  openai: {
    ...ruleProviderCommon,
    behavior: "classical",
    path: "./ruleset/openai.yaml",
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml",
  },
  bard: {
    ...ruleProviderCommon,
    behavior: "classical",
    path: "./ruleset/bard.yaml",
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BardAI/BardAI.yaml",
  },
  bing: {
    ...ruleProviderCommon,
    behavior: "classical",
    path: "./ruleset/bing.yaml",
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bing/Bing.yaml",
  },
  copilot: {
    ...ruleProviderCommon,
    behavior: "classical",
    path: "./ruleset/copilot.yaml",
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.yaml",
  },
  claude: {
    ...ruleProviderCommon,
    behavior: "classical",
    path: "./ruleset/claude.yaml",
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.yaml",
  },
  // 去广告
  reject_non_ip_no_drop: {
    ...ruleProviderCommon,
    format: "text",
    behavior: "classical",
    path: "./rule_set/sukkaw_ruleset/reject_non_ip_no_drop.txt",
    url: "https://ruleset.skk.moe/Clash/non_ip/reject-no-drop.txt",
  },
  reject_non_ip_drop: {
    ...ruleProviderCommon,
    format: "text",
    behavior: "classical",
    path: "./rule_set/sukkaw_ruleset/reject_non_ip_drop.txt",
    url: "https://ruleset.skk.moe/Clash/non_ip/reject-drop.txt",
  },
  reject_non_ip: {
    ...ruleProviderCommon,
    format: "text",
    behavior: "classical",
    path: "./rule_set/sukkaw_ruleset/reject_non_ip.txt",
    url: "https://ruleset.skk.moe/Clash/non_ip/reject.txt",
  },
  reject_domainset: {
    ...ruleProviderCommon,
    format: "text",
    behavior: "classical",
    path: "./rule_set/sukkaw_ruleset/reject_domainset.txt",
    url: "https://ruleset.skk.moe/Clash/domainset/reject.txt",
  },
  reject_ip: {
    ...ruleProviderCommon,
    format: "text",
    behavior: "classical",
    path: "./rule_set/sukkaw_ruleset/reject_ip.txt",
    url: "https://ruleset.skk.moe/Clash/ip/reject.txt",
  },
};
// 代理组通用配置
const groupBaseOption = {
  interval: 300,
  timeout: 3000,
  url: "https://cp.cloudflare.com",
  // lazy: true,
  "max-failed-times": 3,
  hidden: false,
  "exclude-filter":
    "(?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置",
  "include-all": false,
};

const rules = [
  // 去广告
  "RULE-SET,reject_non_ip,REJECT",
  "RULE-SET,reject_domainset,REJECT",
  "RULE-SET,reject_non_ip_drop,REJECT-DROP",
  "RULE-SET,reject_non_ip_no_drop,REJECT",
  // 自定义规则开始
  "DOMAIN,yacd.haishan.me,DIRECT",
  "DOMAIN-SUFFIX,open.spotify.com,DIRECT",
  "DOMAIN-KEYWORD,spotify,PROXY",
  "DOMAIN-SUFFIX,micu.hk,DIRECT",
  "DOMAIN-SUFFIX,ii00.cc,DIRECT",
  "DOMAIN-SUFFIX,hxd.as174.com,DIRECT",
  "DOMAIN-SUFFIX,emby.as174.com,PROXY",
  "DOMAIN-SUFFIX,tanhuatv.site,PROXY",
  "PROCESS-NAME,OneDrive,OneDrive",
  "PROCESS-NAME,OneDriveUpdater,OneDrive",
  "DOMAIN-KEYWORD,1drv,OneDrive",
  "DOMAIN-KEYWORD,onedrive,OneDrive",
  "DOMAIN-KEYWORD,skydrive,OneDrive",
  "DOMAIN-SUFFIX,livefilestore.com,OneDrive",
  "DOMAIN-SUFFIX,oneclient.sfx.ms,OneDrive",
  "DOMAIN-SUFFIX,onedrive.com,OneDrive",
  "DOMAIN-SUFFIX,onedrive.live.com,OneDrive",
  "DOMAIN-SUFFIX,photos.live.com,OneDrive",
  "DOMAIN-SUFFIX,sharepoint.com,OneDrive",
  "DOMAIN-SUFFIX,sharepointonline.com,OneDrive",
  "DOMAIN-SUFFIX,skydrive.wns.windows.com,OneDrive",
  "DOMAIN-SUFFIX,spoprod-a.akamaihd.net,OneDrive",
  "DOMAIN-SUFFIX,storage.live.com,OneDrive",
  "DOMAIN-SUFFIX,storage.msn.com,OneDrive",
  "DOMAIN-SUFFIX,eu,PROXY",
  "DOMAIN-SUFFIX,hk,PROXY",
  "DOMAIN-SUFFIX,jp,PROXY",
  "DOMAIN-SUFFIX,kr,PROXY",
  "DOMAIN-SUFFIX,sg,PROXY",
  "DOMAIN-SUFFIX,tw,PROXY",
  "DOMAIN-SUFFIX,uk,PROXY",
  "DOMAIN-SUFFIX,us,PROXY",
  "DOMAIN-SUFFIX,ca,PROXY",
  // 自定义规则结束

  // 规则集合
  "RULE-SET,reject_ip,REJECT",
  "RULE-SET,private,DIRECT",
  "RULE-SET,bing,AIGC",
  "RULE-SET,copilot,AIGC",
  "RULE-SET,bard,AIGC",
  "RULE-SET,openai,AIGC",
  "RULE-SET,claude,AIGC",
  "RULE-SET,steam,PROXY",
  "RULE-SET,telegram_domain,Telegram",
  "RULE-SET,telegram_ip,Telegram",
  "RULE-SET,google_domain,Google",
  "RULE-SET,google_ip,Google",
  "RULE-SET,geolocation-!cn,PROXY",
  "RULE-SET,cn_domain,DIRECT",
  "RULE-SET,cn_ip,DIRECT",
  "MATCH,PROXY",
];

// 程序入口
function main() {
  const config = {};
  config["dns"] = dnsConfig;

  config["proxy-groups"] = [
    {
      ...groupBaseOption,
      name: "PROXY",
      type: "select",
      proxies: ["AUTO"],
      "include-all": true,
      icon: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Orz-3/mini/master/Color/Static.png",
    },
    {
      ...groupBaseOption,
      name: "AUTO",
      type: "url-test",
      tolerance: 50,
      "include-all": true,
      icon: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Orz-3/mini/master/Color/Urltest.png",
    },
    {
      ...groupBaseOption,
      name: "Telegram",
      type: "select",
      proxies: ["PROXY", "AUTO", "DIRECT"],
      "include-all": true,
      icon: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Orz-3/mini/master/Color/Telegram.png",
    },
    {
      ...groupBaseOption,
      name: "AIGC",
      type: "select",
      proxies: ["PROXY", "AUTO", "DIRECT"],
      "include-all": true,
      icon: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Orz-3/mini/master/Color/OpenAI.png",
    },
    {
      ...groupBaseOption,
      name: "Google",
      type: "select",
      proxies: ["PROXY", "AUTO", "DIRECT"],
      "include-all": true,
      icon: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Orz-3/mini/master/Color/Google.png",
    },
    {
      ...groupBaseOption,
      name: "OneDrive",
      type: "select",
      proxies: ["PROXY", "DIRECT"],
      "include-all": true,
      icon: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Orz-3/mini/master/Color/Microsoft.png",
    },
  ];

  config["rule-providers"] = ruleProviders;
  config["rules"] = rules;

  return config;
}

const config = main();

export default config;